YourNourishment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('login.urls')),
    path('', include('blog.urls')),
    path('', include('activity.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/',views.blog, name='blog'),
    path('blog/id1/',views.article1, name='article1'),
    path('blog/id2/',views.article2, name='article2'),
    path('blog/id3/',views.article3, name='article3'),
    
] 

home/urls.py
from django.urls import path

from . import views

from .views import *


app_name = 'home'

urlpatterns = [

    path('', views.homepage, name='homepage'),
    path('base/', views.base, name='base'),
    path('create_testi/', views.create_testi, name='create_testi'),
    path('testi/', views.testi, name='testi'),

    path('', homepage, name='homepage'),
    path('base/', base, name='base'),

    # dilanjutkan ...
]

home/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
from django.core.validators import MaxValueValidator, MinValueValidator

class Testimoni(models.Model):
    nama = models.CharField(max_length=100)
    usia = models.PositiveIntegerField(default=17,
        	validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
            ])
    pesan = models.TextField()


# Create your models here.

home/forms.py
from . import models
from django import forms
from datetime import datetime, date

class TestimoniForm(forms.Form):
	nama = forms.CharField(
		widget=forms.TextInput(attrs={'required' : 'True', 'class':'form-control'})
							)
	usia = forms.IntegerField()
				
	pesan = forms.CharField(
		widget=forms.Textarea(attrs={'required' : 'True', 'class':'form-control'})
							)

home/views.py
from django.shortcuts import render,redirect
from .models import Testimoni
from .forms import TestimoniForm

from django.shortcuts import render


# Create your views here.

def homepage(request):
    return render(request, 'homepage.html')

def base(request):
    return render(request, 'base.html')


# def create_testi(request):
#     return render(request, 'create_testi.html')

def create_testi(request):
	if request.method == "POST":
		form = TestimoniForm(request.POST)
		if form.is_valid():
			hasil = Testimoni(nama = form.data['nama'], usia = form.data['usia'], pesan = form.data['pesan'])
			hasil.save()
		return redirect("home:testi")
	else :
		form = TestimoniForm()
	return render(request, 'create_testi.html', {'form':form})
	# if request.method == "POST":
	# 	forms = form.TestimoniForm(request.POST)
	# 	if forms.is_valid():
	# 		nama = forms.cleaned_data["nama"]
	# 		usia = forms.cleaned_data["usia"]
	# 		pesan = forms.cleaned_data["pesan"]
	# 		testimoni = Testimoni.objects.create(
	# 			nama=nama,
	# 			usia= usia,
	# 			pesan=pesan,
	# 			)
	# 		testimoni.save()
	# 		return redirect("home:create_testi")
	# forms = form.TestimoniForm()
	# data = Testimoni.objects.all()
	# return render(request, 'create_testi.html', {
	# 	"form": forms,
	# 	"data": data
	# 	}
	# )

def testi(request):
	data = Testimoni.objects.all()
	return render(request, 'testi.html', {"data": data})

home/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Start Your Healthy Life Here!</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity=" sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <link rel="stylesheet" href="{% static 'css/story4.css' %}">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/YNstyle.css' %}">

  </head>
  <body>

      <div class="rect">
        <h3>Help You to Slove Problems in Nutritions and Activites</h3>
      </div>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
        <a class="navbar-brand" href="{% url 'home:homepage' %}"><strong>Your </br> Nourishment</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="../activity">Activity</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../blog">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../testi">Testimoni</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Contact Us
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Instagram</a>
                <a class="dropdown-item" href="#">Whatsapp</a>
                <a class="dropdown-item" href="#">Email</a>
              </div>
            </li>
            <li class="nav-item btn btn-primary navlogin">
              <a class="nav-link" href="../add_login" style="color: white"><b>Login</b></a>
            </li>
          </ul>
        </div>
      </nav>
  {% block content %}
  {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity=" sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>


</html>

home/templates/create_testi.html
{% extends 'base.html' %}	

{% load static %}
{% block content %}

<div class="backgroundputih">
	<div class="jumbotron jumbotron-fluid header">
  		<div class="container">
    		<h1 class="display-4 title">Create Your Testi!</h1>
    		<p class="lead message"> Please kindly give us your honest opinion about our application</p>
  		</div>
	</div>

	<form action="{% url 'home:create_testi' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    
    <input class="btn submit" type="submit" value="Submit">
  </form> 
</div>

{% endblock %}

home/templates/home.html
<!doctype html>

<html lang="en">
 <head>
 	<title>Start Your Healthy Life Here!</title>
 </head>

<body>
	HELLO WORLD!
</body>

</html>

home/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block content %}

	<!-- <div class = "color-black; text-align-center; font-family-'Roboto'; font-weight-bold; font-italic; font-size-36px"> -->
	<div class = "container" style = "margin-top:100px">
	<div class = "row">
	<div class = "col-sm-6">
		<table style = "display: inline-table">
		<tbody>
			<tr>
				<td rowspan = "3"><img src = "{% static 'images/health4.jpg' %}" class = "img-fluid rounded float-right" style = "width: 400px"/></td>
				<td colspan = "2"><img src = "{% static 'images/health3.jpg' %}" class = "img-fluid rounded-top float-left" style = "width: 280px"/></td>
			</tr>
			<tr>
				<td><img src = "{% static 'images/health5.jpg' %}" class = "img-fluid float-left" style = "width: 140px"/></td>
				<td><img src = "{% static 'images/health1.jpg' %}" class = "img-fluid float-left" style = "width: 140px"/></td>
			</tr>
			<tr>
				<td colspan = "2"><img src = "{% static 'images/health2.jpg' %}" class = "img-fluid rounded-bottom float-left" style = "width: 280px"/></td>
			</tr>
		</tbody>
		</table>
		<br/>
		<br/>
		<br/>
		<h2 style = "text-align: center">"Healthy is a Choice"</h2>
		<br/>
		<br/>
		<br/>
	</div>
	<div class = "col-sm-6">
		<br/><br/><br/>
		<p style = "color: black; text-align: center; font-family: Roboto; font-weight: bold; font-size: 24px">
		"Increasing public awareness on health through adequate nutrition food and fitness activities"</p><br/><br/><br/>
		<p style = "color: black; text-align: center; font-family: Roboto; font-weight: bold; font-size: 24px">
		We provide any consultation and recomendation about healthy food and best activity for your body
		so you can get healthy more than now. We can be trusted because based on experienced of the best doctors.
		Join us if you want to be health more.</p>
	</div>
	</div>
	</div>
	</div>

{% endblock %}
=======
<!doctype html>

<html lang="en">
 <head>
 	<title>Start Your Healthy Life Here!</title>
 </head>

<body>
	<h1>WOI KERJAINN!! </h1>
</body>

</html>
>>>>>>> utility

home/templates/testi.html
{% extends 'base.html' %}	

{% load static %}
{% block content %}

<div class="background">
	<div class="jumbotron jumbotron-fluid header1">
  		<div class="container">
    		<h1 class="display-4 title">Our User Testimony!</h1>
    		<p class="lead message">Our application has satisfied many people. Are you ready to be the next one?</p>
  		</div>
	</div>

  {% for testi in data %}

  <div class="card testicard" style="width: 25rem;">
    <div class="card-body">
      <h5 class="card-title ">{{testi.nama}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{testi.usia}} years old</h6>
      <p class="card-text">{{testi.pesan}}</p>
    </div>
  </div>
    
  {% endfor %}
	<a class = "btn btn-primary btnaddtesti" href="{% url 'home:create_testi' %}">Add Testimoni</a>

</div>

{% endblock %}